### ISSUE TITLE
Locker Crash: Cannot read property 'bson_serializer' of null

### ISSUE THREAD

**Issue by nym** [LockerProject/Locker#100]
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Cannot read property 'bson_serializer' of null
    at new Collection (/Users/tomlong/code/l/Locker/node_modules/mongodb/lib/mongodb/collection.js:84:9)
    at /Users/tomlong/code/l/Locker/Common/node/lmongoclient.js:36:57
    at /Users/tomlong/code/l/Locker/Common/node/lmongoclient.js:28:13
    at /Users/tomlong/code/l/Locker/node_modules/mongodb/lib/mongodb/db.js:53:30
    at [object Object].<anonymous> (/Users/tomlong/code/l/Locker/node_modules/mongodb/lib/mongodb/connections/server.js:89:12)
    at [object Object].emit (events.js:64:17)
    at Socket.<anonymous> (/Users/tomlong/code/l/Locker/node_modules/mongodb/lib/mongodb/connection.js:44:10)
    at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:830:27)
    at EventEmitter._tickCallback (node.js:126:26)

**Comment by amcjen** [comment]
Hey Tom, does this happen after you run an "npm update"?  I was seeing some issue with the mongo node module today and it fixed up when I updated.

**Comment by nym** [comment]
This only happened once, but it's the only time that the locker actually crashed on me... not sure what caused it, we can close this if you want.

**Comment by nym** [comment]
Closing per Chris: "i think it was related to a mongo version"
