### ISSUE TITLE
Contacts Collection Dies

### ISSUE THREAD

**Issue by rand** [LockerProject/Locker#110]
[11:14:41][Locker] Looking for providers of type contact/facebook,contact/twitter,contact/google,contact/foursquare,contact/github
[11:14:41][Contacts Collection] svc facebook [ 'contact/facebook', 'link/facebook' ]

[11:14:41][Contacts Collection][ERROR] 

[11:14:41][Contacts Collection][ERROR] /Users/sixwing/src/Locker/node_modules/request/main.js:189

[11:14:41][Contacts Collection][ERROR]   if (!options.httpModule) throw new Error("Invalid protocol");

[11:14:41][Contacts Collection][ERROR]  
[11:14:41][Contacts Collection][ERROR]                ^

[11:14:41][Contacts Collection][ERROR] Error: Invalid protocol
    at [object Object].request (/Users/sixwing/src/Locker/node_modules/request/main.js:189:34)
    at Function.request [as get](/Users/sixwing/src/Locker/node_modules/request/main.js:315:5)
    at Object.getContacts (/Users/sixwing/src/Locker/Collections/Contacts/sync.js:65:13)
    at /Users/sixwing/src/Locker/Collections/Contacts/sync.js:33:29
    at Array.forEach (native)
    at /Users/sixwing/src/Locker/Collections/Contacts/sync.js:30:22
    at [object Object].callback (/Users/sixwing/src/Locker/Common/node/locker.js:70:9)
    at IncomingMessage.<anonymous> (/Users/sixwing/src/Locker/node_modules/request/main.js:260:21)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)

[11:14:41][Locker] contacts process has ended.

**Comment by ctide** [comment]
Fixed: https://github.com/LockerProject/Locker/commit/3cf99e0353f255948d6a65ea5b3a7f3186b5f3cc
