### ISSUE TITLE
missing pkginfo in deps?

### ISSUE THREAD

**Issue by hackervera** [LockerProject/Locker#151]
Installing from new linux system, after i do npm install i run node lockerd.js

tyler@tyler-Aspire-5740:~/Locker$ node lockerd.js 

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'pkginfo'
    at Function._resolveFilename (module.js:317:11)
    at Function._load (module.js:262:25)
    at require (module.js:346:19)
    at Object.<anonymous> (/home/tyler/Locker/node_modules/winston/lib/winston.js:14:1)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/home/tyler/Locker/Common/node/logger.js:10:15)

**Comment by hackervera** [comment]
looks like colors is also missing

**Comment by ctide** [comment]
Those are both dependencies of Winston, not of the locker project itself.  I'm not sure why npm install would install Winston, but not it's dependencies.  I tested this on my OSX machine and it installed everything correctly.  What does your `npm ls` look like after a clean install on your machine?  Specifically the Winston part, which should look like:

├─┬ winston@0.3.5 
│ ├── colors@0.5.0 
│ ├─┬ loggly@0.3.6 
│ │ └── timespan@2.2.0 
│ └── pkginfo@0.2.2

**Comment by meeech** [comment]
I'm seeing this problem as well. deps of loggly don't seem to be installing. osx
