### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by nym** [LockerProject/Locker#179]
My locker crashed after adding Facebook, then waiting about a minute, and then adding Twitter.

/Users/tomlong/code/geoweb/Common/node/ijod.js:23
        this.dataFile = fs.openSync(process.cwd() + "/" + lconfig.me + "/" + d
                                            ^
Error: Too many open files
    at new IJOD (/Users/tomlong/code/geoweb/Common/node/ijod.js:23:45)
    at Object.addCollection (/Users/tomlong/code/geoweb/Common/node/synclet/datastore.js:31:39)
    at processData (/Users/tomlong/code/geoweb/Common/node/lsyncmanager.js:267:19)
    at /Users/tomlong/code/geoweb/Common/node/lsyncmanager.js:247:53
    at /Users/tomlong/code/geoweb/node_modules/async/lib/async.js:97:13
    at Array.forEach (native)
    at /Users/tomlong/code/geoweb/node_modules/async/lib/async.js:26:24
    at Object.forEach (/Users/tomlong/code/geoweb/node_modules/async/lib/async.js:96:9)
    at /Users/tomlong/code/geoweb/Common/node/lsyncmanager.js:247:15
    at Object.init (/Users/tomlong/code/geoweb/Common/node/synclet/datastore.js:19:23)

**Comment by othiym23** [comment]
Just leaving the locker running for about 10 minutes led my dev locker (fresh Me/ directory, use-ui branch) to crash with this bug as well.

**Comment by ctide** [comment]
Fixed in f2a98de9b3522c1c8c2b7695d41286cbc1e24169
