### ISSUE TITLE
29 Aug 09:28:36 - error: [Locker] (node) warning: possible EventEmitter memory leak detected. %d listeners added.

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#180]
29 Aug 09:28:36 - error: [Locker](node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.
29 Aug 09:28:36 - error: [Locker] Trace: 
    at [object Object].<anonymous> (events.js:126:17)
    at [object Object].once (events.js:147:8)
    at /home/mdz/src/singly/Locker/node_modules/winston/lib/winston/transports/file.js:124:19
    at [object Object].open (/home/mdz/src/singly/Locker/node_modules/winston/lib/winston/transports/file.js:159:3)
    at [object Object].log (/home/mdz/src/singly/Locker/node_modules/winston/lib/winston/transports/file.js:115:10)
    at [object Object].log (/home/mdz/src/singly/Locker/node_modules/winston/lib/winston/logger.js:164:17)
    at Object.log (/home/mdz/src/singly/Locker/Common/node/lconsole.js:50:12)
    at proxyRequest (/home/mdz/src/singly/Locker/Ops/webservice.js:272:13)
    at Object.<anonymous> (/home/mdz/src/singly/Locker/Ops/webservice.js:242:5)
    at param (/home/mdz/src/singly/Locker/node_modules/connect/lib/middleware/router.js:147:21)

...and then a couple of minutes later...

29 Aug 09:30:28 - info: [Locker] proxying POST /Me/links/events to http://localhost:18044//events
29 Aug 09:30:28 - info: [Locker] Proxy complete
29 Aug 09:30:28 - info: [Locker] proxying POST /Me/places/events to http://localhost:18045//events
29 Aug 09:30:28 - info: [Locker] Proxy complete
29 Aug 09:30:28 - error: [Links] QUEUE SIZE: 1

29 Aug 09:30:28 - info: [Links] Going to add http://www.gizmag.com/signalguru/19643/

29 Aug 09:30:28 - error: [Links](node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.
29 Aug 09:30:28 - error: [Links] Trace: 
    at [object Object].<anonymous> (events.js:126:17)
    at [object Object].once (events.js:147:8)
    at /home/mdz/src/singly/Locker/node_modules/winston/lib/winston/transports/file.js:124:19
    at [object Object].open (/home/mdz/src/singly/Locker/node_modules/winston/lib/winston/transports/file.js:159:3)
    at [object Object].log (/home/mdz/src/singly/Locker/node_modules/winston/lib/winston/transports/file.js:115:10)
    at [object Object].log (/home/mdz/src/singly/Locker/node_modules/winston/lib/winston/logger.js:164:17)
    at Object.log (/home/mdz/src/singly/Locker/Common/node/lconsole.js:50:12)
    at Socket.<anonymous> (/home/mdz/src/singly/Locker/Common/node/lservicemanager.js:339:21)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:673:31)
29 Aug 09:30:28 - info: [Links] Added http://www.gizmag.com/signalguru/19643/

29 Aug 09:30:28 - error: [Links] QUEUE SIZE: 0

29 Aug 09:30:28 - info: [Locker] proxying GET /favicon.ico to http://localhost:18042/favicon.ico
29 Aug 09:30:29 - debug: Firing an event for link from links action(new)
29 Aug 09:30:29 - info: [Links] Going to add http://www.politico.com/news/stories/0811/62241.html

29 Aug 09:30:29 - info: [Links] Added http://www.politico.com/news/stories/0811/62241.html

29 Aug 09:30:29 - error: [Links] QUEUE SIZE: 0

**Comment by smurthas** [comment]
looks like it is related to logging to files, but not to the console

**Comment by temas** [comment]
So I've isolated this to a winston issue.  It is a warning and non leaking, but I will be filing an issue with them.

**Comment by temas** [comment]
Can be tracked here https://github.com/indexzero/winston/pull/34
