### ISSUE TITLE
Foursquare sync fails

### ISSUE THREAD

**Issue by amcjen** [LockerProject/Locker#181]
When first authorizing foursquare on the new "Setup your Locker" page, I get this in the console.  Wiping the Me/ directory and re-running it gives the same result.

29 Aug 13:27:07 - error: [Locker] SyntaxError: Unexpected end of input
29 Aug 13:27:07 - error: [Locker] 
29 Aug 13:27:07 - error: [Foursquare Account friends] 

29 Aug 13:27:07 - error: [Foursquare Account friends] /Volumes/Data/opt/locker/Connectors/foursquare/friends.js:38

29 Aug 13:27:07 - error: [Foursquare Account friends]         var userID = self.id;

29 Aug 13:27:07 - error: [Foursquare Account friends]                          ^

29 Aug 13:27:07 - error: [Foursquare Account friends] TypeError: Cannot read property 'id' of undefined
    at [object Object].callback (/Volumes/Data/opt/locker/Connectors/foursquare/friends.js:38:26)
    at IncomingMessage.<anonymous> (/Volumes/Data/opt/locker/node_modules/request/main.js:260:21)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at CleartextStream.ondata (http.js:1227:22)
    at CleartextStream._push (tls.js:303:27)
    at SecurePair.cycle (tls.js:574:20)
    at EncryptedStream.write (tls.js:96:13)
    at Socket.ondata (stream.js:36:26)
    at Socket.emit (events.js:64:17)

**Comment by ctide** [comment]
For what it's worth, this is due to rate limiting.  The fix for this is to make error messages a lot clearer, which I will take on.
