### ISSUE TITLE
Search fails in a mysterious way when there is no data (indexed?)

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#185]
The search app displays:

An error has occurred: {"stack":"Error: socket hang up\n    at Socket.<anonymous> (http.js:1286:45)\n    at Socket.emit (events.js:64:17)\n    at Array.2 (net.js:831:12)\n    at EventEmitter._tickCallback (node.js:126:26)","message":"socket hang up"}

and the console shows:

30 Aug 12:15:13 - info: [Search] proxying GET /Me/search/query?q=ubuntu to http://localhost:18045//query?q=ubuntu
30 Aug 12:15:13 - error: [Locker Search] 

30 Aug 12:15:13 - error: [Locker Search] undefined:1

30 Aug 12:15:13 - error: [Locker Search] dz/src/singly/Lo

30 Aug 12:15:13 - error: [Locker Search] ^^

30 Aug 12:15:13 - error: [Locker Search] SyntaxError: Unexpected token ILLEGAL
    at Object.parse (native)
    at [object Object].callback (/home/mdz/src/singly/Locker/Apps/Search/lib/lockersearch/index.js:35:31)
    at IncomingMessage.<anonymous> (/home/mdz/src/singly/Locker/node_modules/request/main.js:260:21)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1227:22)
    at Socket._onReadable (net.js:683:27)
    at IOWatcher.onReadable [as callback](net.js:177:10)

30 Aug 12:15:13 - info: [Locker] searchapp process has ended. (1:null)

**Comment by amcjen** [comment]
This issue should be fixed as of the latest searchresults branch merge.
