### ISSUE TITLE
401 baby!! followed by SyntaxError

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#192]
31 Aug 13:50:16 - info: [Locker] Synclet contacts starting for gcontacts
31 Aug 13:50:16 - info: [Locker] Synclet users starting for github
31 Aug 13:50:16 - info: [Locker] Synclet timeline starting for twitter
31 Aug 13:50:16 - error: [Google Contacts Account contacts] 401 baby!!

31 Aug 13:50:16 - error: [Google Contacts Account contacts] 

31 Aug 13:50:16 - error: [Google Contacts Account contacts] undefined:1

31 Aug 13:50:16 - error: [Google Contacts Account contacts] 

31 Aug 13:50:16 - error: [Google Contacts Account contacts] ^^

31 Aug 13:50:16 - error: [Google Contacts Account contacts] SyntaxError: Unexpected token ILLEGAL
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/mdz/src/singly/Locker/node_modules/gdata-js/gdata.js:103:33)
    at IncomingMessage.emit (events.js:64:17)
    at HTTPParser.onBody (http.js:121:23)
    at CleartextStream.ondata (http.js:1227:22)
    at CleartextStream._push (tls.js:303:27)
    at SecurePair.cycle (tls.js:574:20)
    at EncryptedStream.write (tls.js:96:13)
    at Socket.ondata (stream.js:36:26)
    at Socket.emit (events.js:64:17)

31 Aug 13:50:16 - error: [Locker] SyntaxError: Unexpected end of input
31 Aug 13:50:16 - error: [Locker]

**Comment by smurthas** [comment]
I'm on this - I've found at least one problem..fix coming soon!

**Comment by smurthas** [comment]
This is be resolved in commit r97ae445
