### ISSUE TITLE
2 Sep 10:38:27 - error: [Search] Received a 404 when attempting to enrich search results

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#197]
2 Sep 10:38:27 - error: [Search] Received a 404 when attempting to enrich search results

2 Sep 10:38:27 - error: [Locker Search] 

2 Sep 10:38:27 - error: [Locker Search] undefined:1

2 Sep 10:38:27 - error: [Locker Search] en attempting to
^^

2 Sep 10:38:27 - error: [Locker Search] SyntaxError: Unexpected token ILLEGAL
    at Object.parse (native)
    at [object Object].callback (/home/mdz/src/singly/Locker/Apps/Search/lib/lockersearch/index.js:40:35)
    at IncomingMessage.<anonymous> (/home/mdz/src/singly/Locker/node_modules/request/main.js:260:21)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1227:22)
    at Socket._onReadable (net.js:683:27)
    at IOWatcher.onReadable [as callback](net.js:177:10)

2 Sep 10:38:27 - info: [Locker] searchapp process has ended. (1:null)
2 Sep 10:38:36 - info: [Locker] proxying GET /Me/links/state to http://localhost:18046//state
2 Sep 10:38:36 - info: [Locker] Proxy complete
2 Sep 10:38:46 - info: [Locker] proxying GET /Me/links/state to http://localhost:18046//state
2 Sep 10:38:46 - info: [Locker] Proxy complete

**Comment by amcjen** [comment]
This should be resolved with the searchresults merge
