### ISSUE TITLE
[Links] TypeError: Cannot convert null to object

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#203]
7 Sep 09:50:19 - debug: Firing an event for link from links action(new)
7 Sep 09:50:19 - error: [Links] 
/home/mdz/src/singly/Locker.migration-test/Collections/Links/dataStore.js:99

7 Sep 09:50:19 - error: [Links]         delete doc["_hash"];

7 Sep 09:50:19 - error: [Links]         ^

7 Sep 09:50:19 - error: [Links] TypeError: Cannot convert null to object
    at DELETE (native)
    at /home/mdz/src/singly/Locker.migration-test/Collections/Links/dataStore.js:99:9
    at [object Object].<anonymous> (/home/mdz/src/singly/Locker.migration-test/node_modules/mongodb/lib/mongodb/collection.js:586:30)
    at [object Object].emit (events.js:67:17)
    at [object Object].<anonymous> (/home/mdz/src/singly/Locker.migration-test/node_modules/mongodb/lib/mongodb/connections/server.js:98:12)
    at [object Object].emit (events.js:64:17)
    at Socket.<anonymous> (/home/mdz/src/singly/Locker.migration-test/node_modules/mongodb/lib/mongodb/connection.js:108:16)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:678:14)
    at IOWatcher.onReadable [as callback](net.js:177:10)

**Comment by mdz** [comment]
Note this was with the current production code (d628fd07c557ee7df110a07c0d3715d4b8cc78b9), not current master.

**Comment by ctide** [comment]
This was resolved in 7b179eee473c17d6cabffe8ef42972617f33e0e3
