### ISSUE TITLE
Running multiple lockers on the same machine.

### ISSUE THREAD

**Issue by ghost** [LockerProject/Locker#206]
Hi,

Can we have multiple locker instances running on the same server. If yes how ?

Thanks.

**Comment by ctide** [comment]
Shouldn't be a problem, just need to copy over config.json.example (in the Config directory) to config.json and change the ports for mongo and locker for each instance of the locker you're running.

**Comment by othiym23** [comment]
Singly's entire hosting strategy is built around hosting multiple locker instances per server, so the answer is yes, but it requires some work, and right now inevitably involves virtualization. Our current strategy involves using Linux containers (LXC), but we've also looked at using Xen with very small domU instances and qemu virtual environments.

As far as getting multiple lockers running on a single server without virtualization, the picture's a little murkier. It's possible to give each locker its own MongoDB instance with a little hacking, but right now Node fires up so many HTTP listeners on localhost that a certain amount of overlap is hard to avoid. So look at virtualization if you want to get multiple lockers up and running.

**Comment by ctide** [comment]
One other thing to note, currently you probably want to increment port numbers by about 100 if you aren't using virtualization.  So, first locker uses the default 8042 with mongo at 27018, next should be 8142 / 27118 and so on.  That should ensure you don't have any conflicts.  If you do, let us know though!

**Comment by ghost** [comment]
Hi,

I tried to run locker on a different port.
My Config/config.json file is as follows -
{
"lockerHost" : "localhost",
"lockerPort" : 8142,
"logFile": null,
"me" : "Me",
"scannedDirs" : [
"Apps",
"Collections",
"Connectors"
],
"mongo" : {
"dataDir": "mongodata",
"host": "localhost",
"port": 27118
}
}

when i try to access my locker on the browser , i get the following error -
TypeError: Cannot read property 'length' of undefined
at Object.urlParse as parse
at proxied (/home/devrelay/LockerSetup/Locker/Ops/webservice.js:440:17)
at Router. (/home/devrelay/LockerSetup/Locker/Ops/webservice.js:424:5)
at done (/home/devrelay/LockerSetup/Locker/node_modules/express/lib/router/index.js:250:22)
at middleware (/home/devrelay/LockerSetup/Locker/node_modules/express/lib/router/index.js:244:9)
at param (/home/devrelay/LockerSetup/Locker/node_modules/express/lib/router/index.js:227:11)
at pass (/home/devrelay/LockerSetup/Locker/node_modules/express/lib/router/index.js:232:6)
at Router._dispatch (/home/devrelay/LockerSetup/Locker/node_modules/express/lib/router/index.js:255:4)
at Object.handle (/home/devrelay/LockerSetup/Locker/node_modules/express/lib/router/index.js:45:10)
at next (/home/devrelay/LockerSetup/Locker/node_modules/connect/lib/http.js:201:15)

why is this happening ?
Thanks.
