### ISSUE TITLE
UseUI breaks things for a time!

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#295]
When using use UI, it seems to spawn very slowly on startup, during this time attempts to get the locker pages just error out with:

TypeError: Cannot read property 'instance' of undefined
    at Router.<anonymous> (/home/elsmorian/Locker/Ops/webservice.js:438:33)
    at done (/home/elsmorian/Locker/node_modules/express/lib/router/index.js:250:22)
    at middleware (/home/elsmorian/Locker/node_modules/express/lib/router/index.js:244:9)
    at param (/home/elsmorian/Locker/node_modules/express/lib/router/index.js:227:11)
    at pass (/home/elsmorian/Locker/node_modules/express/lib/router/index.js:232:6)
    at Router._dispatch (/home/elsmorian/Locker/node_modules/express/lib/router/index.js:255:4)
    at Object.handle (/home/elsmorian/Locker/node_modules/express/lib/router/index.js:45:10)
    at next (/home/elsmorian/Locker/node_modules/connect/lib/http.js:201:15)
    at /home/elsmorian/Locker/node_modules/connect/lib/middleware/session.js:323:9
    at /home/elsmorian/Locker/node_modules/connect/lib/middleware/session.js:342:9

After 2 minutes or so of starting locker, the useUI spawns and then things start working again.

**Comment by elsmorian** [comment]
OK, Fixed this hanging, was caused by lack of Clucene lib :)

**Comment by smurthas** [comment]
This is still a bug, fixing right now...
