### ISSUE TITLE
Keep seeing errors in my locker log

### ISSUE THREAD

**Issue by ctide** [LockerProject/Locker#458]
I was on the IDR branch, so might be related to that:

18 Nov 10:14:23 - error: /development/Locker/Apps/UseUI/dashboard-client.js:207

18 Nov 10:14:23 - error:             if(eventInfo[type].count > last[type].count) {
                                                 ^

18 Nov 10:14:23 - error: TypeError: Cannot read property 'count' of undefined
    at /development/Locker/Apps/UseUI/dashboard-client.js:207:50
    at /development/Locker/node_modules/async/lib/async.js:105:25
    at Request.callback (/development/Locker/Apps/UseUI/dashboard-client.js:189:13)
    at Request.<anonymous> (/development/Locker/node_modules/request/main.js:314:21)
    at Request.emit (events.js:64:17)
    at IncomingMessage.<anonymous> (/development/Locker/node_modules/request/main.js:295:19)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1231:22)
    at Socket._onReadable (net.js:683:27)

18 Nov 10:15:15 - error: TypeError: Cannot read property 'length' of undefined
    at Object.urlParse [as parse](url.js:94:27)
    at proxied (/development/Locker/Ops/webservice.js:544:17)
    at Router.<anonymous> (/development/Locker/Ops/webservice.js:520:42)
    at done (/development/Locker/node_modules/express/lib/router/index.js:250:22)
    at middleware (/development/Locker/node_modules/express/lib/router/index.js:244:9)
    at param (/development/Locker/node_modules/express/lib/router/index.js:227:11)
    at pass (/development/Locker/node_modules/express/lib/router/index.js:232:6)
    at Router._dispatch (/development/Locker/node_modules/express/lib/router/index.js:255:4)
    at Object.handle (/development/Locker/node_modules/express/lib/router/index.js:45:10)
    at next (/development/Locker/node_modules/connect/lib/http.js:201:15)
18 Nov 10:15:17 - info: proxying GET /socket.io/1/?t=1321640117514 to undefined/socket.io/1/?t=1321640117514
18 Nov 10:15:17 - error: TypeError: Cannot read property 'length' of undefined
    at Object.urlParse [as parse](url.js:94:27)
    at proxied (/development/Locker/Ops/webservice.js:544:17)
    at Router.<anonymous> (/development/Locker/Ops/webservice.js:520:42)
    at done (/development/Locker/node_modules/express/lib/router/index.js:250:22)
    at middleware (/development/Locker/node_modules/express/lib/router/index.js:244:9)
    at param (/development/Locker/node_modules/express/lib/router/index.js:227:11)
    at pass (/development/Locker/node_modules/express/lib/router/index.js:232:6)
    at Router._dispatch (/development/Locker/node_modules/express/lib/router/index.js:255:4)
    at Object.handle (/development/Locker/node_modules/express/lib/router/index.js:45:10)
    at next (/development/Locker/node_modules/connect/lib/http.js:201:15)
18 Nov 10:15:21 - info: proxying GET /socket.io/1/?t=1321640121516 to undefined/socket.io/1/?t=1321640121516
18 Nov 10:15:21 - error: TypeError: Cannot read property 'length' of undefined
    at Object.urlParse [as parse](url.js:94:27)
    at proxied (/development/Locker/Ops/webservice.js:544:17)
    at Router.<anonymous> (/development/Locker/Ops/webservice.js:520:42)
    at done (/development/Locker/node_modules/express/lib/router/index.js:250:22)
    at middleware (/development/Locker/node_modules/express/lib/router/index.js:244:9)
    at param (/development/Locker/node_modules/express/lib/router/index.js:227:11)
    at pass (/development/Locker/node_modules/express/lib/router/index.js:232:6)
    at Router._dispatch (/development/Locker/node_modules/express/lib/router/index.js:255:4)
    at Object.handle (/development/Locker/node_modules/express/lib/router/index.js:45:10)
    at next (/development/Locker/node_modules/connect/lib/http.js:201:15)

**Comment by temas** [comment]
That's the error I'm seeing from contact being removed from the state.json.  Eric is applying a fix.

**Comment by amcjen** [comment]
Added a fix to ensure contacts doesn't get blown away from re-running migrations.  Speaks more to the big migration epic, but should be good now.
