### ISSUE TITLE
TypeError: Invalid argument to getAgent

### ISSUE THREAD

**Issue by prakashrai838** [LockerProject/Locker#48]
TypeError: Invalid argument to getAgent
    at Object.getAgent (http.js:1446:11)
    at _getAgent (/opt/quartzjer-Locker-00632d2/node_modules/http-proxy/lib/node-http-proxy.js:48:30)
    at [object Object].proxyRequest (/opt/quartzjer-Locker-00632d2/node_modules/http-proxy/lib/node-http-proxy.js:377:12)
    at proxied (/opt/quartzjer-Locker-00632d2/Ops/webservice.js:336:11)
    at Object.<anonymous> (/opt/quartzjer-Locker-00632d2/Ops/webservice.js:329:5)
    at param (/opt/quartzjer-Locker-00632d2/node_modules/connect/lib/middleware/router.js:147:21)
    at pass (/opt/quartzjer-Locker-00632d2/node_modules/connect/lib/middleware/router.js:163:10)
    at Object.router [as handle](/opt/quartzjer-Locker-00632d2/node_modules/connect/lib/middleware/router.js:169:6)
    at next (/opt/quartzjer-Locker-00632d2/node_modules/connect/lib/http.js:204:15)
    at Object.handle (/opt/quartzjer-Locker-00632d2/Ops/webservice.js:39:21)

Whenever I used to connect using url http://localhost:8042 above error cames. So please help me out. 
Thank you.......

**Comment by nwl** [comment]
I also have this issue:

levine@groucho-ubuntu:~/Locker$ node -v
v0.5.0-pre

Seems fixed in later version of node:

https://github.com/nodejitsu/node-http-proxy/issues/38

**Comment by szarecor** [comment]
Per the trace, the error is in Locker/node_modules/http-proxy/lib/node-http-proxy.js

recent versions of node are expecting a different method signature for http.getAgent.

In node-http-proxy.js, update _getAgent to look something like this:
<code>
function _getAgent (host, port, secure) {
  //var agent = !secure ? http.getAgent(host, port) : https.getAgent({ 
  //  host: host, 
  //  port: port 
  //});
  var opts = { 
    host: host, 
    port: port 
  }; 
  var agent = !secure ? http.getAgent(opts) : https.getAgent(opts);  
  agent.maxSockets = maxSockets;
  return agent;
}
</code>

And you should be all set.

**Comment by ctide** [comment]
Please use the latest released version of Node.  As of today, that is 0.4.8: https://github.com/joyent/node/tree/v0.4.8
