### ISSUE TITLE
After merging imthemap, some apps appear as 'undefined' and don't work

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#543]
They seem to be the ones which were previously "installed' from Github.

**Comment by mdz** [comment]
Clicking on them yields:

TypeError: Cannot read property 'length' of undefined
    at Object.urlParse [as parse](url.js:94:27)
    at proxied (/home/mdz/src/singly/Locker/Ops/webservice.js:466:17)
    at /home/mdz/src/singly/Locker/Ops/webservice.js:275:17
    at Object.spawn (/home/mdz/src/singly/Locker/Common/node/lservicemanager.js:231:16)
    at proxyRequest (/home/mdz/src/singly/Locker/Ops/webservice.js:274:28)
    at Router.<anonymous> (/home/mdz/src/singly/Locker/Ops/webservice.js:205:9)
    at done (/home/mdz/src/singly/Locker/node_modules/express/lib/router/index.js:250:22)
    at middleware (/home/mdz/src/singly/Locker/node_modules/express/lib/router/index.js:244:9)
    at param (/home/mdz/src/singly/Locker/node_modules/express/lib/router/index.js:227:11)
    at pass (/home/mdz/src/singly/Locker/node_modules/express/lib/router/index.js:232:6)

**Comment by temas** [comment]
I believe this is fixed now, but will be verified after the imthmap merge as it's part of the immediately next dashboard story.

**Comment by smurthas** [comment]
@temas, can you verify that this behavior is gone?

**Comment by temas** [comment]
Can not reproduce, @mdz can you verify on your locker.

**Comment by mdz** [comment]
Can't reproduce on latest
