### ISSUE TITLE
offline (no dns) causes shutdown

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#570]
18 Jan 04:47:55 - info: total of 0+0+0 and threshold 50 so setting tolerance to 2
18 Jan 04:50:10 - info: registry update from http://registry.singly.com/-/all/since?stale=update_after&startkey=1326829502282
18 Jan 04:50:10 - error: { stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'ECONNREFUSED, Could not contact DNS servers',
  errno: 11,
  code: 'ECONNREFUSED' }
18 Jan 04:50:10 - error: 'Error: ECONNREFUSED, Could not contact DNS servers\n    at dns.js:194:15\n    at Object.lookup (dns.js:190:11)\n    at Socket.connect (net.js:718:20)\n    at Object.createConnection (net.js:265:5)\n    at Agent._getConnection (http.js:1365:15)\n    at Agent._establishNewConnection (http.js:1180:21)\n    at Agent._cycle (http.js:1405:10)\n    at Agent.appendMessage (http.js:1162:8)\n    at Object._requestFromAgent (http.js:1437:27)\n    at Object.request (http.js:1450:18)'

18 Jan 04:50:10 - info: Shutting down...
18 Jan 04:50:10 - info: Shutdown complete.

What is strange is, the request.get() SHOULD call the callback and pass this as the error object, and in testing when offline it does, but somehow this was thrown to the whole process??

**Comment by mdz** [comment]
I see this too
