### ISSUE TITLE
Twitter - update existing friends link breaks

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#67]
```
[09:54:04][Twitter Account][ERROR] 
/Users/temas/singly/code/Locker/Connectors/Twitter/sync.js:206
                    var eventObj = {source:type, type:'update', data:person};
                    ^

[09:54:04][Twitter Account][ERROR] ReferenceError: person is not defined
    at /Users/temas/singly/code/Locker/Connectors/Twitter/sync.js:206:21
    at Statement.<anonymous> (/Users/temas/singly/code/Locker/node_modules/sqlite/sqlite.js:130:11)
```

Repeatable every time I try and do it.

**Comment by smurthas** [comment]
Yep, erictj caught this last night - fix on the way!

**Comment by smurthas** [comment]
Fixed in dev.
