### ISSUE TITLE
Failure publishing app locally

### ISSUE THREAD

**Issue by kristjan** [LockerProject/Locker#709]
```
3 Feb 11:02:19 - info: registry publishing kristjan-prolific_posters
3 Feb 11:02:19 - info: attempting to publish Me/github/kristjan/prolific_posters/package.json
3 Feb 11:02:19 - info: adding user {"name":"6dd67eea0a7966ed80ef4a3fb5f43414","salt":"na","password_sha":"...","email":"c4c44107b7acf39fcd786915a5f0409e@singly.com","_id":"org.couchdb.user:6dd67eea0a7966ed80ef4a3fb5f43414","type":"user","roles":[],"date":"2012-02-03T19:02:19.579Z"}
npm ERR! prepublish Error: undefined log message
npm ERR! prepublish     at log (/Users/kristjan/src/Locker/node_modules/npm/lib/utils/log.js:112:11)
npm ERR! prepublish     at lifecycle (/Users/kristjan/src/Locker/node_modules/npm/lib/utils/lifecycle.js:23:3)
npm ERR! prepublish     at /Users/kristjan/src/Locker/node_modules/npm/lib/publish.js:36:5
npm ERR! prepublish     at readJson (/Users/kristjan/src/Locker/node_modules/npm/lib/utils/read-json.js:21:12)
npm ERR! prepublish     at EventEmitter.publish (/Users/kristjan/src/Locker/node_modules/npm/lib/publish.js:33:3)
npm ERR! prepublish     at Object.<anonymous> (/Users/kristjan/src/Locker/node_modules/npm/lib/npm.js:193:11)
npm ERR! prepublish     at /Users/kristjan/src/Locker/Ops/registry.js:419:34
npm ERR! prepublish     at cb (/Users/kristjan/src/Locker/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:36:9)
{ data: { issue: [ [Object] ] } }
[dashboardv3] 
[dashboardv3] fs.js:400
[dashboardv3]   return binding.stat(path);
[dashboardv3]                  [dashboardv3] ^[dashboardv3] 
[dashboardv3] Error: ENOENT, No such file or directory '/Users/kristjan/src/Locker/Me/github/kristjan/prolific_posters/screenshot'
    at Object.statSync (fs.js:400:18)
    at Request.callback (/Users/kristjan/src/Locker/Apps/dashboardv3/dashboard-client.js:246:39)
    at Request.<anonymous> (/Users/kristjan/src/Locker/node_modules/request/main.js:314:21)
    at Request.emit (events.js:64:17)
    at IncomingMessage.<anonymous> (/Users/kristjan/src/Locker/node_modules/request/main.js:295:19)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Socket.ondata (http.js:1227:22)
    at Socket._onReadable (net.js:683:27)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
```

**Comment by kristjan** [comment]
This may've happened because I neither uploaded a photo nor set a URL for one.

**Comment by quartzjer** [comment]
the prepublish stuff is all normal (npm spits that out to stderr, part of the node 0.4x ver of npm we have to use afaict), but the lack of screenshot is the real bug here, this is being fixed in #682 too so I'm on it :)
