### ISSUE TITLE
Twitter Connector - crashes on /getNew/friends

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#78]
dev branch

[09:39:41][Locker] Proxying a get to /getNew/friends to service /Me/twitter/getNew/friends
[09:39:41][Locker] proxying GET /Me/twitter/getNew/friends to http://localhost:18043//getNew/friends
[09:39:41][Locker] Proxy complete
[09:39:48][Twitter Account][ERROR] 
/Users/temas/singly/code/Locker/node_modules/request/main.js:189
  if (!options.httpModule) throw new Error("Invalid protocol");
                                 ^

[09:39:48][Twitter Account][ERROR] Error: Invalid protocol
    at [object Object].request (/Users/temas/singly/code/Locker/node_modules/request/main.js:189:34)
    at request (/Users/temas/singly/code/Locker/node_modules/request/main.js:315:5)
    at Function.post (/Users/temas/singly/code/Locker/node_modules/request/main.js:343:10)
    at Object.event (/Users/temas/singly/code/Locker/Common/node/locker.js:74:13)
    at EventEmitter.<anonymous> (/Users/temas/singly/code/Locker/Connectors/Twitter/sync-api.js:116:16)
    at EventEmitter.emit (events.js:64:17)
    at /Users/temas/singly/code/Locker/Connectors/Twitter/sync.js:189:30
    at /Users/temas/singly/code/Locker/node_modules/mongodb/lib/mongodb/collection.js:348:9
    at [object Object].<anonymous> (/Users/temas/singly/code/Locker/node_modules/mongodb/lib/mongodb/db.js:335:5)
    at [object Object].emit (events.js:67:17)

[09:39:48][Locker] twitter process has ended.

**Comment by temas** [comment]
Getting this on most of the connector urls.  Get profile worked so far.
