### ISSUE TITLE
Crash on downloading plugin

### ISSUE THREAD

**Issue by jamii** [LockerProject/Locker#8]
From fresh install of commit 8d6a5de:

Run 'node locker.js'
Navigate to localhost:8042
Click services
Click chrome history
Click install
See:
Installed: {"title":"Chrome History","action":"Sync your browser history from Chrome","desc":"Collect and sync my browser history from Chrome.","run":"node client.js","provides":["link/chrome"],"srcdir":"Connectors/ChromeHistory","is":"connector","id":"b54754d31a45abb7cfc983d19b7d7354","me":"/home/jamie/Locker/Me/b54754d31a45abb7cfc983d19b7d7354","uri":"http://localhost:8042/Me/b54754d31a45abb7cfc983d19b7d7354/"}
Navigate to localhost:8042 (to ensure the service is visible)
Click page link next to Chrome History
See:
great! do you need to install the plugin?
Click plugin link.
locker crashes.

Log:

jamie@jamie-aspire:~/Locker$ node locker.js 
[01:19:21][Locker] Spawned dashboard pid: 7095
[01:19:21][Locker] locker running at http://localhost:8042/
[01:19:21][Locker] generating id private key
[01:19:22][Locker] generating id public key
[01:19:22][Locker] id keys loaded
[01:19:22][Locker] dashboard stdout: http://localhost:18042/

[01:19:28][Locker] proxying / to http://localhost:18042/
[01:19:29][Locker] proxying /date.js to http://localhost:18042/date.js
[01:19:29][Locker] proxying /util.js to http://localhost:18042/util.js
[01:19:30][Locker][ERROR] Error sending diary: Error: ENOENT, No such file or directory 'Me/diary/2011/2/31.json'
[01:19:30][Locker] proxying /favicon.ico to http://localhost:18042/favicon.ico
[01:20:10][Locker] proxying /post2install?id=0 to http://localhost:18042/post2install?id=0
[01:20:10][Locker] dashboard stdout: { output: [ 'POST /install HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\nec\r\n{"title":"Chrome History","action":"Sync your browser history from Chrome","desc":"Collect and sync my browser history from Chrome.","run":"node client.js","provides":["link/chrome"],"srcdir":"Connectors/ChromeHistory","is":"connector"}\r\n0\r\n\r\n' ],
  outputEncodings: [ undefined ],
  writable: true,
  _last: true,
  chunkedEncoding: true,
  shouldKeepAlive: false,
  useChunkedEncodingByDefault: true,
  _hasBody: true,
  _trailer: '',
  finished: true,
  method: 'POST',
  path: '/install',
  _headers: { 'content-type': 'application/x-www-form-urlencoded' },
  _headerNames: { 'content-type': 'Content-Type' },
  _header: 'POST /install HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n',
  _headerSent: true }

[01:20:10][Locker] /install
[01:20:10][Locker] installing {"title":"Chrome History","action":"Sync your browser history from Chrome","desc":"Collect and sync my browser history from Chrome.","run":"node client.js","provides":["link/chrome"],"srcdir":"Connectors/ChromeHistory","is":"connector"}
[01:20:11][Locker] proxying /favicon.ico to http://localhost:18042/favicon.ico
[01:20:15][Locker] proxying /favicon.ico to http://localhost:18042/favicon.ico
[01:21:17][Locker] proxying / to http://localhost:18042/
[01:21:18][Locker] proxying /favicon.ico to http://localhost:18042/favicon.ico
[01:21:21][Locker] proxying / to http://localhost:18042/
[01:21:21][Locker] proxying /date.js to http://localhost:18042/date.js
[01:21:21][Locker] proxying /util.js to http://localhost:18042/util.js
[01:21:22][Locker][ERROR] Error sending diary: Error: ENOENT, No such file or directory 'Me/diary/2011/2/31.json'
[01:21:22][Locker] proxying /favicon.ico to http://localhost:18042/favicon.ico
[01:24:22][Chrome History] proxying /Me/c638801c4fb3759985c239f9da53c0c4/ to http://localhost:18043/
[01:24:23][Locker] proxying /favicon.ico to http://localhost:18042/favicon.ico
[01:25:00][Locker] proxying /Me/c638801c4fb3759985c239f9da53c0c4/plugin to http://localhost:18043/plugin
[01:25:00][Chrome History][ERROR] DEBUG: ./crxmake.sh 301c5b594e592d2bbb08a07226266fbc4fb3438c /home/jamie/Locker/Me/key

[01:25:00][Chrome History][ERROR] DEBUG: ./crxmake.sh 6f3f4940e8ace319dbaf49daef219f340139c887 /home/jamie/Locker/Me/key

[01:25:00][Chrome History][ERROR] DEBUG: Error:./crxmake.sh: 22: Bad substitution

[01:25:00][Chrome History][ERROR] DEBUG: Error:./crxmake.sh: 23: Bad substitution

[01:25:00][Chrome History][ERROR] DEBUG: Wrote 6f3f4940e8ace319dbaf49daef219f340139c887.crx

http.js:550
    throw new Error("Can't render headers after they are sent to the client.")
          ^
Error: Can't render headers after they are sent to the client.
    at ServerResponse._renderHeaders (http.js:550:11)
    at ServerResponse.writeHead (http.js:783:20)
    at Request.<anonymous> (/home/jamie/Locker/Ops/webservice.js:247:13)
    at Request.emit (events.js:45:17)
    at Request._respond (/usr/local/lib/node/.npm/wwwdude/0.0.5/package/lib/wwwdude.js:219:36)
    at Request._handleResponse (/usr/local/lib/node/.npm/wwwdude/0.0.5/package/lib/wwwdude.js:125:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node/.npm/wwwdude/0.0.5/package/lib/wwwdude.js:157:14)
    at IncomingMessage.emit (events.js:59:20)
    at HTTPParser.onMessageComplete (http.js:111:23)
    at Client.onData [as ondata](http.js:1442:27)

**Comment by jamii** [comment]
The exception takes down the main locker process but leaves other node processes running. Restarting locker fails with: 

jamie@jamie-aspire:~/Locker$ node locker.js 
[01:27:21][Locker] Installing c638801c4fb3759985c239f9da53c0c4
[01:27:21][Locker] Spawned dashboard pid: 7169
[01:27:21][Locker] locker running at http://localhost:8042/
[01:27:21][Locker] id keys loaded
[01:27:22][Locker] dashboard stdout: http://localhost:18042/

[01:27:22][Locker] Error dashboard: 

[01:27:22][Locker] Error dashboard: node.js:116

[01:27:22][Locker] Error dashboard:         throw e; // process.nextTick error, or 'error' event on first tick

[01:27:22][Locker] Error dashboard:         ^

[01:27:22][Locker] Error dashboard: Error: EADDRINUSE, Address already in use
    at HTTPServer._doListen (net.js:1062:5)
    at net.js:1033:14
    at Object.lookup (dns.js:132:45)
    at HTTPServer.listen (net.js:1027:20)
    at Object.<anonymous> (/home/jamie/Locker/Ops/Dashboard/dashboard.js:188:5)
    at Module._compile (module.js:383:26)
    at Object..js (module.js:389:10)
    at Module.load (module.js:315:31)
    at Function._load (module.js:276:12)
    at Array.<anonymous> (module.js:402:10)

[01:27:22][Locker] dashboard died with code 1

**Comment by temas** [comment]
So the comment issue is a more annoying one due to the crash in the core and needing to find a way to cleanup the children processes in that case.  We'll deal with that later, and could you spin it off as a new issue?

The plugin issue is proving to be rather nasty.  The first part of the issue had to do with the way the file was sent causing a redirect.  This redirect handler would send headers, but then after the successful redirect more headers were attempted to be sent.  Once that issue was resolved the plugin is now not loading by Chrome.  Still under investigation.

**Comment by smurthas** [comment]
This code has been deprecated.
