### ISSUE TITLE
Clicking icons for services not in apikeys file results in ugly error 

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#801]
For example, clicking one of the icons the the list of services an app uses that is not in apikeys opens a popup to /auth/_ClickedService_ which contains:

TypeError: Cannot read property 'appKey' of undefined
    at authRedir (/home/elsmorian/NewLocker/Ops/registry.js:561:70)
    at authIsAwesome (/home/elsmorian/NewLocker/Ops/registry.js:537:19)
    at callbacks (/home/elsmorian/NewLocker/node_modules/express/lib/router/index.js:272:11)
    at param (/home/elsmorian/NewLocker/node_modules/express/lib/router/index.js:246:11)
    at param (/home/elsmorian/NewLocker/node_modules/express/lib/router/index.js:243:11)
    at pass (/home/elsmorian/NewLocker/node_modules/express/lib/router/index.js:253:5)
    at Router._dispatch (/home/elsmorian/NewLocker/node_modules/express/lib/router/index.js:280:4)
    at Object.handle (/home/elsmorian/NewLocker/node_modules/express/lib/router/index.js:45:10)
    at next (/home/elsmorian/NewLocker/node_modules/connect/lib/http.js:203:15)
    at /home/elsmorian/NewLocker/node_modules/connect/lib/middleware/session.js:323:9

**Comment by elsmorian** [comment]
Note clicking Instagram generates the above error, as does Facebook, and GContacts. Twitter and Flickr generate a single line saying it cant find the require apikeys.

**Comment by mdz** [comment]
I thought the icons were supposed to be hidden unless API keys were available
