### ISSUE TITLE
Error while installing GoogleContacts

### ISSUE THREAD

**Issue by temas** [LockerProject/Locker#84]
TypeError: Cannot read property 'available' of undefined
    at Object.<anonymous> (/Users/temas/singly/code/Locker/Ops/Dashboard/dashboard-client.js:70:17)
    at nextMiddleware (/Users/temas/singly/code/Locker/node_modules/express/lib/router/index.js:139:34)
    at param (/Users/temas/singly/code/Locker/node_modules/express/lib/router/index.js:147:16)
    at pass (/Users/temas/singly/code/Locker/node_modules/express/lib/router/index.js:155:10)
    at Object.router [as handle](/Users/temas/singly/code/Locker/node_modules/express/lib/router/index.js:161:6)
    at next (/Users/temas/singly/code/Locker/node_modules/express/node_modules/connect/lib/http.js:204:15)
    at /Users/temas/singly/code/Locker/node_modules/connect/lib/middleware/session.js:296:9
    at /Users/temas/singly/code/Locker/node_modules/connect/lib/middleware/session.js:311:9
    at Array.0 (/Users/temas/singly/code/Locker/node_modules/connect/lib/middleware/session/memory.js:57:7)
    at EventEmitter._tickCallback (node.js:126:26)

**Comment by temas** [comment]
Worked on a reload and install again.

**Comment by ctide** [comment]
Is https://github.com/LockerProject/Locker/issues/105 the same issue?
