### ISSUE TITLE
warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by othiym23** [LockerProject/Locker#895]
May not be an actual problem, but see this now when running tests, and in logs on production:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
    at ClientRequest.<anonymous> (events.js:139:15)
    at ClientRequest.once (events.js:160:8)
    at IncomingMessage.<anonymous> (/private/srv/projects/singly/locker-lockerproject-git/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:344:22)
    at IncomingMessage.emit (events.js:88:20)
    at Object.resume (/private/srv/projects/singly/locker-lockerproject-git/node_modules/http-proxy/lib/node-http-proxy.js:252:18)
    at [object Object].proxyRequest (/private/srv/projects/singly/locker-lockerproject-git/node_modules/http-proxy/lib/node-http-proxy/http-proxy.js:382:16)
    at [object Object].proxyRequest (/private/srv/projects/singly/locker-lockerproject-git/node_modules/http-proxy/lib/node-http-proxy/routing-proxy.js:192:9)
    at proxied (/private/srv/projects/singly/locker-lockerproject-git/Ops/webservice.js:523:11)
    at /private/srv/projects/singly/locker-lockerproject-git/Ops/webservice.js:303:17
    at /private/srv/projects/singly/locker-lockerproject-git/Common/node/lservicemanager.js:334:24
```

**Comment by quartzjer** [comment]
This is a known issue, I submitted https://github.com/nodejitsu/node-http-proxy/pull/206 to fix it. I don't /believe/ it has any actual impact other than being noisy.

**Comment by mdz** [comment]
The noisiness is a real issue; I see tracebacks go by in the logs and it makes my nerves tingle.

@quartzjer - you got a followup on your pull request asking for some changes

**Comment by othiym23** [comment]
Closing as resolved, eventually. 🚢
