### ISSUE TITLE
No response when navigating to Facebook Account page

### ISSUE THREAD

**Issue by jamii** [LockerProject/Locker#9]
From fresh install of commit 8d6a5de:

Run 'node locker.js'
Navigate to localhost:8042
Click services
Click facebook account
Click install
See:
Installed: {"title":"Facebook Account","action":"Connect to a Facebook account","desc":"Collect and sync my (open graph) data from my Facebook account using Facebook Connect and a Facebook 'app' that I create just for myself.","run":"node client.js","provides":["contact/facebook","status/facebook"],"srcdir":"Connectors/Facebook","is":"connector","id":"07f90329de90ab99d8ecae6dc6d107b2","me":"/home/jamie/Locker/Me/07f90329de90ab99d8ecae6dc6d107b2","uri":"http://localhost:8042/Me/07f90329de90ab99d8ecae6dc6d107b2/"}
Navigate to localhost:8042
Click services
Click on page link next to Facebook Account
Loading icon spins but page does not load
Chrome developer toolbar says request is waiting for reponse.

Log:
jamie@jamie-aspire:~$ !git 
git clone https://github.com/quartzjer/Locker.git 
Initialized empty Git repository in /home/jamie/Locker/.git/
cd Lockerremote: Counting objects: 1267, done.
remote: Compressing objects: 100% (759/759), done.
remote: Total 1267 (delta 657), reused 880 (delta 426)
Receiving objects: 100% (1267/1267), 538.42 KiB | 146 KiB/s, done.
Resolving deltas: 100% (657/657), done.
jamie@jamie-aspire:~$ cd Locker
jamie@jamie-aspire:~/Locker$ sudo npm install
[sudo] password for jamie: 
npm info it worked if it ends with ok
npm info using npm@0.3.15
npm info using node@v0.4.2
npm info calculating sha1 /usr/local/lib/node/.npm/.cache/locker/0.0.0/package.tgz
npm info shasum 444696057c6f7b92b58d15608d406189a35d1dab
npm info preinstall locker@0.0.0
npm info install locker@0.0.0
npm info postinstall locker@0.0.0
npm info predeactivate locker@0.0.0
npm info deactivate locker@0.0.0
npm info postdeactivate locker@0.0.0
npm info preactivate locker@0.0.0
npm info activate locker@0.0.0
npm info postactivate locker@0.0.0
npm info build Success: locker@0.0.0
npm ok
jamie@jamie-aspire:~/Locker$ node locker.js 
[01:44:27][Locker] Spawned dashboard pid: 7302
[01:44:27][Locker] locker running at http://localhost:8042/
[01:44:27][Locker] generating id private key
[01:44:27][Locker] generating id public key
[01:44:27][Locker] id keys loaded
[01:44:27][Locker] dashboard stdout: http://localhost:18042/

[01:44:34][Locker] proxying / to http://localhost:18042/
[01:44:35][Locker] proxying /date.js to http://localhost:18042/date.js
[01:44:35][Locker] proxying /util.js to http://localhost:18042/util.js
[01:44:37][Locker][ERROR] Error sending diary: Error: ENOENT, No such file or directory 'Me/diary/2011/2/31.json'
[01:44:37][Locker] proxying /favicon.ico to http://localhost:18042/favicon.ico
[01:44:50][Locker] proxying /post2install?id=5 to http://localhost:18042/post2install?id=5
[01:44:50][Locker] dashboard stdout: { output: [ 'POST /install HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n151\r\n{"title":"Facebook Account","action":"Connect to a Facebook account","desc":"Collect and sync my (open graph) data from my Facebook account using Facebook Connect and a Facebook \'app\' that I create just for myself.","run":"node client.js","provides":["contact/facebook","status/facebook"],"srcdir":"Connectors/Facebook","is":"connector"}\r\n0\r\n\r\n' ],
  outputEncodings: [ undefined ],
  writable: true,
  _last: true,
  chunkedEncoding: true,
  shouldKeepAlive: false,
  useChunkedEncodingByDefault: true,
  _hasBody: true,
  _trailer: '',
  finished: true,
  method: 'POST',
  path: '/install',
  _headers: { 'content-type': 'application/x-www-form-urlencoded' },
  _headerNames: { 'content-type': 'Content-Type' },
  _header: 'POST /install HTTP/1.1\r\nContent-Type: application/x-www-form-urlencoded\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n',
  _headerSent: true }

[01:44:50][Locker] /install
[01:44:50][Locker] installing {"title":"Facebook Account","action":"Connect to a Facebook account","desc":"Collect and sync my (open graph) data from my Facebook account using Facebook Connect and a Facebook 'app' that I create just for myself.","run":"node client.js","provides":["contact/facebook","status/facebook"],"srcdir":"Connectors/Facebook","is":"connector"}
[01:45:05][Locker] proxying /favicon.ico to http://localhost:18042/favicon.ico
[01:46:31][Locker] proxying / to http://localhost:18042/
[01:46:31][Locker] proxying /date.js to http://localhost:18042/date.js
[01:46:31][Locker] proxying /util.js to http://localhost:18042/util.js
[01:46:32][Locker][ERROR] Error sending diary: Error: ENOENT, No such file or directory 'Me/diary/2011/2/31.json'
[01:46:33][Locker] proxying /favicon.ico to http://localhost:18042/favicon.ico
[01:46:36][Facebook Account][ERROR] 

[01:46:36][Facebook Account][ERROR] node.js:116

[01:46:36][Facebook Account][ERROR]         throw e; // process.nextTick error, or 'error' event on first tick

[01:46:36][Facebook Account][ERROR]         ^

[01:46:36][Facebook Account][ERROR] Error: Cannot find module 'request'
    at Function._resolveFilename (module.js:299:11)
    at Function._load (module.js:245:25)
    at require (module.js:327:19)
    at Object.<anonymous> (/home/jamie/Locker/Common/node/locker.js:2:15)
    at Module._compile (module.js:383:26)
    at Object..js (module.js:389:10)
    at Module.load (module.js:315:31)
    at Function._load (module.js:276:12)
    at require (module.js:327:19)
    at Object.<anonymous> (/home/jamie/Locker/Connectors/Facebook/client.js:17:14)

**Comment by temas** [comment]
Adding the request module v1.9.5 to the required packages.

Closed by 673ac7f33d33fc4105071eebd11b6db5d1026c8d
