### ISSUE TITLE
In cases where credentials don't match for a redirect, handle the error rather than looping

### ISSUE THREAD

**Issue by rand** [LockerProject/Locker#90]

**Comment by rand** [comment]
[19:21:37][Foursquare Account][ERROR] DEBUG: redirecting to http://localhost:8042/Me/foursquare/auth

[19:21:38][Locker] Proxying a get to /auth/?error=redirect_uri_mismatch to service /Me/foursquare/auth/?error=redirect_uri_mismatch
[19:21:38][Locker] proxying GET /Me/foursquare/auth/?error=redirect_uri_mismatch to http://localhost:18043//auth/?error=redirect_uri_mismatch
[19:21:38][Locker] Proxy complete
[19:21:39][Foursquare Account][ERROR](node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

[19:21:39][Foursquare Account][ERROR] Trace: 
    at EventEmitter.<anonymous> (events.js:126:17)
    at authComplete (/Users/sixwing/src/Locker/Connectors/foursquare/sync-api.js:30:23)
    at /Users/sixwing/src/Locker/Common/node/connector/client_init.js:48:21
    at [object Object].callback (/Users/sixwing/src/Locker/Common/node/connector/oauth2.js:104:9)
    at IncomingMessage.<anonymous> (/Users/sixwing/src/Locker/node_modules/request/main.js:260:21)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at CleartextStream.ondata (http.js:1226:22)
    at CleartextStream._push (tls.js:303:27)
    at SecurePair.cycle (tls.js:574:20)

[19:21:39][Foursquare Account][ERROR](node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

[19:21:39][Foursquare Account][ERROR] Trace: 
    at EventEmitter.<anonymous> (events.js:126:17)
    at authComplete (/Users/sixwing/src/Locker/Connectors/foursquare/sync-api.js:33:23)
    at /Users/sixwing/src/Locker/Common/node/connector/client_init.js:48:21
    at [object Object].callback (/Users/sixwing/src/Locker/Common/node/connector/oauth2.js:104:9)
    at IncomingMessage.<anonymous> (/Users/sixwing/src/Locker/node_modules/request/main.js:260:21)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at CleartextStream.ondata (http.js:1226:22)
    at CleartextStream._push (tls.js:303:27)
    at SecurePair.cycle (tls.js:574:20)
