### ISSUE TITLE
lastfm: TypeError: Cannot read property 'uts' of undefined

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#928]
```
15 Mar 00:27:12 - error: Uncaught exception:
 15 Mar 00:27:12 - error: [TypeError: Cannot read property 'uts' of undefined]
 15 Mar 00:27:12 - error: 'TypeError: Cannot read property \'uts\' of undefined\n    at Connectors/LastFM/scrobbles.js:26:24\n    at /home/Connectors/LastFM/lib.js:199:69\n    at Request._callback (/home/Connectors/LastFM/lib.js:113:25)\n    at Request.callback (/home/node_modules/request/main.js:108:22)\n    at Request.<anonymous> (/home/node_modules/request/main.js:468:18)\n    at Request.emit (events.js:67:17)\n    at IncomingMessage.<anonymous> (/home/nod
 e_modules/request/main.js:429:16)\n    at IncomingMessage.emit (events.js:88:20)\n    at HTTPParser.onMessageComplete (http.js:137:23)\n    at Socket.onend (http.js:1185:16)
```

**Comment by temas** [comment]
Forrest and I got this last night.  ee9842c0f61f67ab19240a9bb2e7d768b86cae49
